version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env.example
    volumes:
      - db-data:/postgresql/data
    ports:
      - 5431:5432



  app:
    build:
      context: .
    env_file:
      - .env.example
    container_name: bewise_test
    command: ["/bewise_test/docker/bd.sh"]
    ports:
      - 8080:8000
    volumes:
      - .env:/bewise_test/.env
    depends_on:
      - db

volumes:
  db-data:
    driver: local